config/routes.rb
IMTS::Application.routes.draw do
  resources :devices do
    member do
      get :update_hmi
      get :update_alarms
      get :update_activity
    end
  end
  resources :apps do
    resources :app_pictures, :only => [:index, :destroy]
  end
  get "login", :to => "sessions#new"
  post "login", :to => "sessions#create"
  get "logout", :to => "sessions#destroy"
  root :to => "devices#index"
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :name, :url, :enabled, :on_time, :off_time, 
                  :description, :location, :logo, :picture, :in_cycle,
                  :logo_cache, :picture_cache, :daily_utilization,
                  :cutting_tool, :quality_report,
                  :has_utilization
                  
  attr_reader :cutting_tool_doc
  
  mount_uploader :logo, LogoUploader
  mount_uploader :picture, PictureUploader
  validates_presence_of :name, :on_time, :off_time,
                       :description, :location, :logo                                           

  has_many :alarms, :dependent => :destroy, :class_name => '::Alarm'
  has_many :cycles, :dependent => :destroy
  has_many :hourly_utilizations, :dependent => :destroy
  
  scope :active, lambda { |*obj| where(:enabled => true) }
  scope :url_not_null, lambda { |*obj| where.not(:url => nil) }
  scope :with_url, lambda { |*obj| where.not(:url => "").merge(self.url_not_null) }

  class DataValue
    attr_reader :component, :component_name, :item, :name, :sub_type, :value 
    def initialize(component, component_name, item, name, sub_type, value)
      @component, @component_name, @item, @name, @sub_type, @value=
        component, component_name, item, name, sub_type, value
      @value.strip!
      if @value && @value.length > 20
        @value = "#{@value[0..20]}..."
      end
      if @value =~ /^[0-9\.]+$/
        @value = @value.to_f.to_s
      end
    end
  end

  class Alarm < DataValue
    attr_reader :code, :state
    def initialize(component, component_name, item, name, sub_type, value,
        code, state)
      super(component, component_name, item, name, sub_type, value)
      @code, @state = code, state
    end
  end

  class Condition < DataValue
    attr_reader :value_type
    def initialize(component, component_name, item, name, sub_type, value,
        value_type)
      super(component, component_name, item, name, sub_type, value)
      @value_type = value_type
    end
  end
  
  class Component 
    attr_accessor :name, :nativeName, :type, :values
    def initialize(name, nativeName, type)
      @name, @nativeName, @type = name, nativeName, type
      @values = []
    end
  end
  
  def get_data
    return [] unless has_url?

    @asset = nil
    dest = URI.parse(self.url)
    client = response = nil
    Timeout::timeout(3) do
      Net::HTTP.start(dest.host, dest.port) do |client|
        response = client.get("#{dest.path}/current")
      end
    end
    if Net::HTTPOK === response
      document = REXML::Document.new(response.body)
      components = []
      @version == "1.0"
      document.each_element('//Header') do |head|
        if head.attributes['version'] == "1.1"
          @version = "1.1"
        end
      end
      document.each_element('//ComponentStream') do |component|
        comp_attrs = component.attributes
        comp = Component.new(comp_attrs['name'] || comp_attrs['componentId'], 
                             comp_attrs['nativeName'], 
                             comp_attrs['component'])
        # Special handling for Spindles
        if comp.type == 'Rotary'
          component.each_element_with_text('SPINDLE', 0, 'Events/RotaryMode') { |v| comp.type = 'Spindle' }
        end
        components << comp
        component.each_element('Events/*|Samples/*|Condition/*') do |value|
          value_attrs = value.attributes
          if value.name == 'Alarm'
            comp.values << Alarm.new(comp_attrs['component'], comp_attrs['name'], value.name, value_attrs['name'], value_attrs['subType'], value.text || "", value_attrs['code'], value_attrs['state'])
          elsif value.parent.name == 'Condition' 
            if value.name != 'Normal' and value.name != 'Unavailable' and value.text != 'UNAVAILABLE'
              comp.values << Condition.new(comp_attrs['component'], comp_attrs['name'], value.name, value_attrs['name'], value_attrs['subType'], value.text || "", value_attrs['type'])
            end
          elsif value.text and value.text != 'UNAVAILABLE' and !value.text.empty?
            comp.values << DataValue.new(comp_attrs['component'], comp_attrs['name'], value.name, value_attrs['name'], value_attrs['subType'], value.text || "")
          else
            next
          end
        end
      end
      
      result = Hash.new { |h, v| h[v] = [] }
      components.delete_if { |c| c.values.empty? }
      components.each { |c| result[c.type] << c }
      result.each { |k, v| v.sort_by { |c| c.name} }
    else
      logger.error "Response from server #{response}"
      []
    end

  rescue Timeout::Error
    logger.error "Request to #{self.url} timed out"
    []

  rescue Errno::ECONNREFUSED, SocketError
    logger.error "Could not connect to #{self.url}"
    []
  
  rescue
    logger.error "#{$!.class}: Unexpected error: #{$!}"
    logger.error $!.backtrace.join("\n")
    []
  end 
  
  def get_asset(asset_id)
    dest = URI.parse(self.url)
    response = asset = nil
    begin
      Timeout::timeout(5) do 
        Net::HTTP.start(dest.host, dest.port) do |client|
          response = client.get("/asset/#{asset_id}")
        end
      end  
      if Net::HTTPOK === response
        asset = REXML::Document.new(response.body)
        asset = nil if asset.root.name != "MTConnectAssets"
      end
    rescue Timeout::Error
    rescue Exception
      logger.error "Error getting asset: #{$!}"
    end
    asset
  end
  
  def has_cutting_tool?
    if defined? @has_cutting_tool
      return @has_cutting_tool
    end
    
    if self.cutting_tool and !self.cutting_tool.empty?
      @cutting_tool_doc = get_asset(self.cutting_tool)
      if  @cutting_tool_doc and @cutting_tool_doc.elements['//CuttingTool']
        @has_cutting_tool = true
      else
        self.update_attributes(:cutting_tool => nil)
        @has_cutting_tool = false
      end
    else
      @has_cutting_tool = false
    end
  end
  
  def has_quality_report?
    self.quality_report? and
      File.exists?("#{Rails.root}/public/quality/#{id}/#{quality_report}.html")
  end
  
  def format_quality_report(asset_id)
    file_name = "/quality/#{id}/#{asset_id}.html"
    full_path = "#{Rails.root}/public/#{file_name}"
    if File.exists?(full_path)
      mtime = File.stat(full_path).mtime.to_i
      "#{file_name}?#{mtime}"
    else
      ""
    end
  end
  
  def generate_quality_report(asset_id, doc = nil)
    file_name = "#{Rails.root}/public/quality/#{id}/#{asset_id}.html"
    logger.info "#{id} - Generating quality report for #{asset_id} to #{file_name}"
    
    Dir.mkdir(File.dirname(file_name)) unless File.exists?(File.dirname(file_name))
    
    doc = get_asset(asset_id) unless doc
    gen = QualityGenerator.new(doc)
    gen.parse
    gen.generate_table(file_name)

  rescue
    logger.error "Parse and generate of quality report failed #{self.id} #{asset_id}: #{$!}"
    logger.error $!.backtrace.join("\n")
  end

  def has_url?
    self.url and !self.url.empty?
  end
  
  def has_asset?
    self.cutting_tool? or self.quality_report?
  end
  
  def show_utilization?
    (self.has_url? and self.has_utilization?) or !has_asset?
  end

  def handle_update(xml)
    document = REXML::Document.new(xml)
    # puts document
    # Check for Execution and ControllerMode      
      
    # Do some initializations only the first time through. 
    unless defined?(@execution); @execution = 'UNAVAILABLE'; end
    unless defined?(@mode); @mode = 'UNAVAILABLE'; end
    
    document.each_element('//Execution|//ControllerMode|//Warning|//Fault|//Normal|//AssetChanged') do |element|      
      case element.name
      when 'ControllerMode'
        @mode = element.text
        logger.info "#{id} - Mode = #{@mode}"
        unless self.has_utilization or @mode == 'UNAVAILABLE'
          self.update_attributes(:has_utilization => true)
        end
        
      when 'Execution'
        @execution = element.text
        logger.info "#{id} - Execution = #{@execution}"
        unless self.has_utilization or @execution == 'UNAVAILABLE'
          self.update_attributes(:has_utilization => true)
        end
        
      when 'Warning', 'Fault'
        timestamp = DateTime.parse(element.attributes['timestamp'])
        
        # Add condition to list for device at timestamp. Only add the text and time.
        # Look for duplicate
        old = alarms.where('time = ? and code = ?', timestamp, 
                          element.attributes['nativeCode'])
        if old.empty?
          logger.info "#{id} - Creating a new alarm: #{element}"
          ::Alarm.create!(device_id: id, 
                        time: timestamp, 
                        alarm_type: element.attributes['type'],
                        severity: element.name,
                        code: element.attributes['nativeCode'],
                        data_item_id: element.attributes['dataItemId'],
                        description: element.text)
        else
          logger.info "#{id} - Skipping alarm #{element}"
        end
        
      when 'Normal'        
        logger.info "#{id} - Received a normal - #{element}"
        code = element.attributes['nativeCode']
        if code.nil? or code.empty?
          old = alarms.where('data_item_id = ? and cleared is NULL', element.attributes['dataItemId'])
        else
          old = alarms.where('data_item_id = ? and code = ? and cleared is NULL', element.attributes['dataItemId'],
                             code)          
        end
        timestamp = DateTime.parse(element.attributes['timestamp'])
        old.each do |alarm|          
          alarm.update_attributes(:cleared => timestamp)
          logger.info "#{id} - Cleared alarm: #{alarm.inspect}"
        end
        
      when 'AssetChanged'
        if element.text != 'UNAVAILABLE'
          begin
            asset_type = element.attributes['assetType']
            logger.info "#{id} - Got asset #{asset_type}"
            gen = false

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :authorize!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    if session[:authorized]    
      @devices = Device.all.order('name') 
      @apps = App.all.order('name') 
    else
      @devices = Device.active.order('name') 
      @apps = App.active.order('name')
      @cache_key = [@devices.max_by(&:updated_at), @apps.max_by(&:updated_at)].
          max_by(&:updated_at).try(:updated_at).to_i.to_s
    end
  end

  def show
    @device = Device.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json { render :json => @device.to_json(:methods => [:elapsed_hourly_utilization, :elapsed_daily_utilization]) }
    end
  end

  def new
    @device = Device.new(:enabled => true, :on_time => 9, :off_time => 19)
  end

  def create
    @device = Device.new(params[:device])
    if @device.save
      flash[:notice] = "Device created successfully."
      expire_fragment('all_devices_and_apps')
      redirect_to devices_path
    else
      flash.now[:error] = "There were problems in creating a device"
      render :new
    end
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update 
    @device = Device.find(params[:id])
    qrf = params[:device].delete('quality_report_file')
    params[:device][:quality_report] = 'SPC_1' if qrf
    if @device.update_attributes(params[:device])
      flash[:notice] = "Device updated successfully"

      if qrf
        doc = REXML::Document.new(qrf.read)
        @device.generate_quality_report('SPC_1', doc)
      end
      expire_fragment('all_devices_and_apps')
      redirect_to devices_path
    else
      flash.now[:error] = "Device was not updated"
      render :new
    end
  end

  def destroy
    @device = Device.find(params[:id])
    if @device.destroy
      flash[:notice] = "Device deleted successfully"
      expire_fragment('all_devices_and_apps')
      redirect_to devices_path
    else
      flash[:notice] = "Device was not deleted"
      redirect_to devices_path
    end
  end

  def update_hmi
    @device = Device.find(params[:id])
    @data = @device.get_data
    render :template => "devices/_hmi", :layout => false
  end

  def update_alarms
    @device = Device.find(params[:id])
    render :template => "devices/_alarms", :layout => false
  end

  def update_activity
    @device = Device.find(params[:id])
    render :template => "devices/_activity", :layout => false
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
  def format_device_app_url(app_url, device_url)
    url = app_url.dup
    if app_url.index("?")
      url << '&'
    else
      url << '?'
    end
    durl = device_url.sub!("localhost", "imts.mtconnect.org")
    url << "device=#{device_url}"
  end
      
  def display_row(text, item)
    res = <<-EOF
    <td class="name">#{text}</td>
    <td class="sub-type">#{item.sub_type}</td>
    EOF
    if (item.is_a? Device::Condition)
      res << %{<td class="value-type">#{item.value_type}</td>}
    end
    res << %{<td class="value">#{item.value}</td>}
    res
  end
end

app/views/devices/_activity.html.haml
.alert.device_state{:class=>@device.state_css_class}
  %strong=@device.state

app/views/devices/_alarms.html.haml
%table.table.table-striped.table-bordered.table-condensed
  %thead
    %tr
      %th Time
      %th Cleared
      %th Code
      %th Description
  %tbody
    -@device.alarms.sort_by(&:time).reverse.each do |alarm|
      %tr{:class=>alarm.severity_class}
        %td=alarm.formatted_time
        %td=alarm.cleared_time
        %td=alarm.code
        %td=alarm.description

app/views/devices/_hmi.html.haml
- if @data.empty?
  %b
    %em
      %br/
      = succeed "The" do
        %br/
      = @device.name
      machine is currently unavailable.
      Please try again in a few minutes.
- else
  .data
    - ['Controller', 'Path', 'Linear', 'Rotary', 'Spindle'].each do |k|
      - items = @data.delete(k)
      - unless items.nil? or items.empty?
        %table
          %tr
            %th{:colspan => "4"}= k
          - items.each do |c|
            - c.values.each do |i|
              - if k == 'Linear' or k == 'Rotary' or k == 'Spindle'
                %tr
                  =raw display_row("#{i.component_name} #{i.item}", i)
              - else
                %tr
                  =raw display_row(i.item, i)
    - @data.each do |k, items|
      - unless items.empty?
        %table
          %tr
            %th{:colspan => "4"}= k
          - items.each do |c|
            - c.values.each do |i|
              %tr
                =raw display_row(i.item, i)

app/views/devices/_tools.html.haml
- if @device.has_cutting_tool? and cutting_tool = @device.cutting_tool_doc.elements['//CuttingTool'] 
  .utilization-row
    .left-utilization
      %h3 Cutting Tool Identity Information
      %h4 The header of the cutting tool document provides indentity information about the cutting tool instance including its unique name, type, and manufactures.
      %br
      %table
        %tr
          %th{:colspan => "2"} Identity
        - cutting_tool.attributes.sort.each do |k, v|
          %tr
            %td.name= k
            %td.value= v
        - if desc = cutting_tool.elements['.//Description']
          %tr
            %th{:colspan => "2"} Description
          - desc.text.split(/[\t]+/).each do |l|
            %tr
              %td{:colspan => "2"}= l
        
     
      %h3 Cutting Tool Life Cycle
      %h4 MTConnect focuses primarily on the cutting tool's life on the shop floor that includes various process parameters about how the tool will be used.
      %br
      
      %table    
        - cutting_tool.elements['.//CuttingToolLifeCycle'].each do |ele|
          - next if ele.is_a? REXML::Text
          - case ele.name            
          - when 'CutterStatus'
            %tr
              %th{:colspan => "2"}= "Cutter Status"
            - ele.each_element('.//Status') do |status|
              %tr
                %td{:colspan => "2"}= status.text
            
          - when 'Measurements', 'CuttingItems'
          - when 'CuttingItem'
            %tr
              %th{:colspan => "2"}= ele.name
            - ele.attributes.sort.each do |k, v|
              %tr
                %td.name= k
                %td.value= v
            
          - else
            %tr
              %th{:colspan => "2"}= ele.name
            - ele.attributes.sort.each do |k, v|
              %tr
                %td.name= k
                %td.value= v
            %tr
              %td.name Current Value
              %td.value= ele.text 

      %h3 Cutting Items    
      %h4 Each individual part of the cutting tool can be measured separately. This allow us to represent each insert in a shell mill or each step in a step drill.
      %br

      %table
        - cutting_tool.each_element('.//CuttingToolLifeCycle/CuttingItems/*') do |ele|
          %tr
            %th{:colspan => "2"} Identity
          - ele.attributes.sort.each do |k, v|
            %tr
              %td.name= k
              %td.value= v

          - ele.each_element('./Measurements/*') do |ele|
            - next if ele.is_a? REXML::Text
            %tr
              %th{:colspan => "2"}= ele.name
            - ele.attributes.sort.each do |k, v|
              %tr
                %td.name= k
                %td.value= v
            %tr
              %td.name Current Value
              %td.value= ele.text         

    .right-utilization
      %h3 Measurements
      %h4 The cutting tool geometries can be called out as a list of measurements. The measurements include a nominal value, optional tolerances, and a measured actual value. 
      %br
      
      %table    
        - cutting_tool.each_element('.//CuttingToolLifeCycle/Measurements/*') do |ele|
          - next if ele.is_a? REXML::Text
          %tr
            %th{:colspan => "2"}= ele.name
          - ele.attributes.sort.each do |k, v|
            %tr
              %td.name= k
              %td.value= v
          %tr
            %td.name Current Value
            %td.value= ele.text         
  

app/views/devices/_utilization.haml
%h2
  Utilization is the percentage of time this device has been executing a part program 
  compared to its scheduled operational time. The data below is a single day’s cycles 
  using MTConnect's real-time event notification capability.
.utilization-row
  %br
  .left-utilization
    %h3 Execution
    #activity
      =render "activity"
  .right-utilization
    %h3 Daily Utilization
    #daily.graph{'data-id' => dom_id(@device)}
.utilization-text
  %br
  .left-utilization
    %h4
      Active indicates the machine is currently Actively Executing a 
      program with the Controller in Automatic Mode.
      In MTConnect this is represented by Execution ACTIVE and 
      ControllerMode AUTOMATIC.
  .right-utilization
    %h4
      Amount of time this device has been executing a part program as a percentage 
      of the total time it is scheduled to be operating today between #{@device.on_time}:00 
      and #{@device.off_time}:00.
.utilization-row
  %br
  .left-utilization.alarms
    %h3 Faults and Warnings
    #alarms
      =render "alarms"
  .right-utilization
    %h3 Hourly Utilization
    #hourly.graph{'data-id' => dom_id(@device)}
.utilization-text
  %br
  .left-utilization
    %h4
      List of reported MTConnect conditions that were either Faults (indicated in red) or Warnings. 
      Table shows the time the fault occurred, time it was cleared, native code 
      on the machine, and description of the fault
  .right-utilization
    %h4
      Hourly utilization shows the time the machine was active during each one
      hour period starting with the beginning of the scheduled day and stopping 
      at the end of the scheduled day.
    
%h5
  %br
  The source is available at 
  %a{:href => "http://github.com/mtconnect/demo", :target => "_blank"}
    http://github.com/mtconnect/demo

app/views/devices/edit.html.haml
=form_for @device, :html => {:class => "well", :multipart => true, :role => 'form' } do |f|
  %h3 Edit device

  - if @device.errors.any?
    .alert.alert-error
      %h4.alert-heading Error(s)!
      - @device.errors.full_messages.each do |msg|
        %p= msg 

  .form-group
    =f.label :name, 'Company Name'
    =f.text_field :name, class: 'form-control'

  .form-group
    =f.label :url, 'The URL for the MTConnect Agent. Should include Device name as well. For example: http://example.com/MyDevice'
    =f.text_field :url, class: 'form-control'

  .form-group
    =f.label :enabled
    =f.check_box :enabled

  .form-group
    =f.label :description
    =f.text_area :description, :class => 'form-control', :rows => 20

  .form-group
    =f.label :location
    = 'Booth Location or Company Locations <City>, <State/Country>'    
    %br
    =f.text_field :location

  .form-group
    =f.label :logo
    %br
    The logo will be resized to fit 270 wide by 130 high for the large image. A smaller
    image will be generated for the main page off of the same image.  The image will 
    be scaled and the aspect ratio preserved.
    %br
    =f.file_field :logo
    =f.hidden_field :logo_cache

  .form-group
    =f.label :picture
    %br
    The logo will be resized to fit 545 wide by 420 high. The image will 
    be scaled and the aspect ratio preserved.
    %br  
    =f.file_field :picture
    =f.hidden_field :picture_cache

  .form-group
    =f.label :on_time, 'Hour production starts (CDT for show)'
    =f.select :on_time, [6, 7, 8, 9, 10, 11, 12]
    %br  
    =f.label :off_time, 'Hour production stops (CDT for show)'
    =f.select :off_time, [15, 16, 17, 18, 19, 20, 21, 22, 23]

  .form_group
    =f.label 'SPC Quality Report'
    =f.file_field :quality_report_file

  %br
  =f.submit

app/views/devices/index.html.haml
-cache_unless(session[:authorized], 'all_devices_and_apps', skip_digest: true) do
  %p
    %h1.select_Manufacturer.white
      Select a Device or an Application below
      %br
      to view MTConnect in action

  #devices.section
    %h1.tab
      =image_tag("text_devices.png", :alt => "Devices", :class => 'device_head')
    .section_top
      =image_tag("section_top.png")
    .section_content
      -if session[:authorized]
        .row
          .col-md-2.col-md-offset-9
            =link_to "New Device", new_device_path, :class => "btn btn-primary"
      %ul
        -@devices.each do |device|
          %li
            %a{:href => device_path(device), :class => 'manufacturer_logo' }
              -if device.logo?
                =image_tag device.logo.thumb.url
              -else
                =device.name
            -if session[:authorized]
              .operations
                =link_to "Edit", edit_device_path(device), :class => "btn btn-primary"
                =link_to "Delete", device_path(device), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-primary"
                -if !device.enabled
                  =image_tag('disabled.png', :alt => 'disabled', :class => 'disabled')
        .clear
    .section_bottom
      =image_tag("section_bottom.png")

  #apps.section
    %h1.tab
      =image_tag('text_applications.png', :alt => "Devices", :class => 'applications_head')
    .section_top
      =image_tag("section_top.png")
    .section_content
      -if session[:authorized]
        .row
          .col-md-2.col-md-offset-9
            =link_to "New Application", new_app_path, :class => "btn btn-primary"
      %ul
        -@apps.each do |app|
          %li
            %a{:href => app_path(app)}
              .manufacturer_logo
                -if app.logo?
                  =image_tag app.logo.thumb.url
                -else
                  =app.name
            -if session[:authorized]
              .operations
                =link_to "Edit", edit_app_path(app), :class => "btn btn-primary"
                =link_to "Delete", app_path(app), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-primary"
                -if !app.enabled
                  =image_tag('disabled.png', :alt => 'disabled', :class => 'disabled')
        .clear
    .section_bottom
      =image_tag("section_bottom.png")

app/views/devices/new.html.haml
=form_for @device, :html => {:class => "well", :multipart => true, :role => 'form' } do |f|
  %h3 New device
  %p Add the details of the device

  - if @device.errors.any?
    .alert.alert-error
      %h4.alert-heading Error(s)!
      - @device.errors.full_messages.each do |msg|
        %p= msg 

  .form-group
    =f.label :name, 'Company Name'
    =f.text_field :name, class: 'form-control'

  .form-group
    =f.label :url, 'The URL for the MTConnect Agent. Should include Device name as well. For example: http://example.com/MyDevice'
    =f.text_field :url, class: 'form-control'

  .form-group
    =f.label :enabled
    =f.check_box :enabled

  .form-group
    =f.label :description
    =f.text_area :description, :class => 'form-control', :rows => 20

  .form-group
    =f.label :location
    = 'Booth Location or Company Locations <City>, <State/Country>'    
    %br
    =f.text_field :location

  .form-group
    =f.label :logo
    %br
    The logo will be resized to fit 270 wide by 130 high for the large image. A smaller
    image will be generated for the main page off of the same image.  The image will 
    be scaled and the aspect ratio preserved.
    %br
    =f.file_field :logo
    =f.hidden_field :logo_cache

  .form-group
    =f.label :picture
    %br
    The logo will be resized to fit 545 wide by 420 high. The image will 
    be scaled and the aspect ratio preserved.
    %br  
    =f.file_field :picture
    =f.hidden_field :picture_cache

  .form-group
    =f.label :on_time, 'Hour production starts (CDT for show)'
    =f.select :on_time, [6, 7, 8, 9, 10, 11, 12]
    %br  
    =f.label :off_time, 'Hour production stops (CDT for show)'
    =f.select :off_time, [15, 16, 17, 18, 19, 20, 21, 22, 23]

  %br
  =f.submit

app/views/devices/show.html.haml
#device
  -cache ['heading', @device] do
    #device-heading
      #device-logo
        -if @device.logo?
          =image_tag @device.logo.button.url
        -else
          =@device.name
      #device-description
        %p.text
          =raw @device.description
        %p.location
          %span=@device.location
    .border
  #device-detail
    -cache ['detail', @device] do
      .device-picture
        -if @device.picture?
          =image_tag @device.picture.display.url
        -else
          No Picture
    .hmi{'data-id' => dom_id(@device)}
      %p.text
        %b
          %em
            %br/
            Please wait...
#device-tabs  
  %ul.nav.nav-tabs
    -if @device.show_utilization?
      %li
        %a{"data-toggle" => "tab", :href => "#utilization"} Utilization
    -if @device.has_cutting_tool?
      %li
        %a{"data-toggle" => "tab", :href => "#cutting_tool"} Cutting Tool 
    -if @device.has_quality_report?
      %li
        %a{"data-toggle" => "tab", :href => "#quality_report"} Quality Report
  .tab-content
    -if @device.show_utilization?
      .tab-pane.fade#utilization
        =render "utilization"
    -if @device.has_cutting_tool?
      .tab-pane.fade#cutting_tool
        .tools
          =render "tools"
    -if @device.has_quality_report?
      .tab-pane.fade#quality_report
        .quality
          %h2
            The following is a Statistical Process Control report analyzing four characteristics.
            Along with the actual measurements, there are eight statistics being computed. Average,
            and standard deviation, Cp (process capability), Cpk (process capability index),
            Pp (process performance), and Ppk (process performance index). The report also provides
            the upper and lower tolerances for the measurements.

          %iframe{"src" => @device.format_quality_report(@device.quality_report)}